### PR TITLE
feat: GEOT-137: Group settings page

### PR DESCRIPTION
**Pull request by bsekula12**

### CODE REVIEW

**Comment by bsekula12** [comment]
First glance on group settings (still missing tests etc)

**Comment by mariusz-kabala** [comment]
add to whitelist

**Comment by mariusz-kabala** [comment]
ok to test

**Comment by mariusz-kabala** [comment]
you have a TS error: 
`packages/app-andrew/src/__test__/components/group-settings/ChangeGroupName/index.test.tsx(8,26): error TS6133: 'queryByText' is declared but its value is never read.`

**Comment by ra8ga** [comment]
retest this please

**Pull request closed without merging**
