### PR TITLE
feat: GEOT-219: add file upload

### PR DESCRIPTION
**Pull request by ra8ga**

### CODE REVIEW

**Comment by rfurmaga** [comment]
@mariusz-kabala 
- where I should add types for "acceptedFiles"
- how to write test for: isDragActive

**Comment by ra8ga** [comment]
@mariusz-kabala

where I should add types for "acceptedFiles"
how to write test for: isDragActive

**Comment by mariusz-kabala** [comment]
@ra8ga you should not add any types, as react-dropzone is already typed. Different story is that it is typed incorrect - the File object does not have path property, this is something extra, added by this lib. And I did not check the implementation so can not tell how much you can rely on it. 

I don't see any reason to use it, but if you have to, you can try to type it like this: 

```
const file: File & { path: string }
```

you do not write tests for external lib. if you want to have this set to true, you mock the lib.

**Comment by rfurmaga** [comment]
> I don't see any reason to use it, but if you have to, you can try to type it like this:

Should I create dropzone without external library? What do you think?

**Comment by ra8ga** [comment]
> I don't see any reason to use it, but if you have to, you can try to type it like this:

Should I create dropzone without external library? What do you think?

**Comment by mariusz-kabala** [comment]
> Should I create dropzone without external library? What do you think?

you can use it, just don't use `path` in File object - as it does not exists, and its not needed

**Pull request merged**
